### ISSUE TITLE
Well Done

### ISSUE THREAD

**Issue by spyke7** [tom-doerr/github_stats#1]
Hey Tom I am Shreejan and I really liked your project. It shows me the stats of my project. I have given a star to your project.
 I have also made a project. This is a memory game named jackpot in python. Please visit my project and give me some feedback and please give it a star. It's a memory game in which you have to say the words in a reverse manner without seeing them. Please give it a star.
 https://github.com/Shreejan-35/JACKPOT

**Comment by tom-doerr** [comment]
How about you post it on reddit to get stars, e.g. in the r/Python subreddit?

**Comment by spyke7** [comment]
ok I will post it. Thank you for your suggestion

**Comment by spyke7** [comment]
Hey tom can you please give me a star on my repo. 
https://github.com/Shreejan-35/JACKPOT
